apiVersion: v1
kind: Secret
metadata:
  name: gitlab-credentials
  labels:
    {{- include "testcity.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.secrets.gitlab.token | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: oltp-headers
  labels:
    {{- include "testcity.labels" . | nindent 4 }}
type: Opaque
stringData:
  value: {{ .Values.secrets.otlp.headers | quote }}
