variables:
  BASE_IMAGE: "registry.kontur.host/ke-forms/test-analytics-gitlab-ci:v5"
  HOUSTON2_TEAM_ID: "07f09d0f-0ee5-4ad4-b585-bc7599374579"

Front tests:
  stage: test
  image:
    name: $BASE_IMAGE
  script:
    - cd Front
    - npm install
    - npm run lint
    - npm run typecheck
    - npm test
  artifacts:
    reports:
      junit: Front/.test-reports/junit.xml

Deploy TestAnalytics:
  stage: deploy
  image:
    name: $BASE_IMAGE
  when: manual
  manual_confirmation: "Подумой..."
  script: .gitlab-ci/deploy.sh