variables:
  BASE_IMAGE: "registry.kontur.host/ke-forms/test-analytics-gitlab-ci:v5"
  HOUSTON2_TEAM_ID: "07f09d0f-0ee5-4ad4-b585-bc7599374579"

Front Typecheck and lint:
  stage: test
  image:
    name: $BASE_IMAGE
  tags:
    - forms-k8s
  script:
    - cd Front
    - npm install
    - npm run lint -- . --format json --output-file eslint-report.json
    - npm run typecheck
  artifacts:
    reports:
      codequality: Front/eslint-report.json
    expire_in: 1 week
    
Front tests:
  stage: test
  image:
    name: $BASE_IMAGE
  tags:
    - forms-k8s
  script:
    - cd Front
    - npm install
    - npm test
  artifacts:
    paths:
      - Front/.test-reports/junit.xml
    reports:
      junit: Front/.test-reports/junit.xml

.DotNet tests:
  stage: test
  image:
    name: $BASE_IMAGE
  tags:
    - forms-k8s
  services:
    - name: clickhouse/clickhouse-server
      alias: clickhouse
  variables:
    CLICKHOUSE_DB: default
    CLICKHOUSE_USER: testanalytics-user
    CLICKHOUSE_PASSWORD: 123123    
  script:
    - export TESTANALYTICS_CLICKHOUSE_HOST="clickhouse"
    - export TESTANALYTICS_CLICKHOUSE_PORT="8123"
    - export TESTANALYTICS_CLICKHOUSE_DB="$CLICKHOUSE_DB"
    - export TESTANALYTICS_CLICKHOUSE_USER="$CLICKHOUSE_USER"
    - export TESTANALYTICS_CLICKHOUSE_PASSWORD="$CLICKHOUSE_PASSWORD"
    - dotnet test --logger "junit;LogFilePath=../.test-reports/{assembly}.test-result.xml;FailureBodyFormat=Verbose"
  artifacts:
    paths:
      - .test-reports/**/*.xml
    reports:
      junit: .test-reports/**/*.xml

Deploy TestAnalytics:
  stage: deploy
  image:
    name: $BASE_IMAGE
  tags:
    - forms-k8s
  when: manual
  allow_failure: true
  script: .gitlab-ci/deploy.sh