variables:
  DEFAULT_SOLUTION_FILE: "TestAnalytics.sln"
  BASE_IMAGE: "registry.kontur.host/ke-forms/gitlab-ci:11938"
  HOUSTON2_TEAM_ID: "07f09d0f-0ee5-4ad4-b585-bc7599374579"

Deploy TestAnalytics:
  stage: deploy
  image:
    name: $BASE_IMAGE
  when: manual
  manual_confirmation: "Подумой..."
  script: .gitlab-ci/deploy.sh