image: node:16

pages:
  stage: deploy
  environment: production
  script:
    - cd Front
    - npm ci
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - idevops


