services:
  clickhouse:
    image: "clickhouse/clickhouse-server:24.8-alpine"
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: testanalytics-user
      CLICKHOUSE_PASSWORD: 123123
    volumes:
      - clickhouse_data:/var/lib/clickhouse
  kafka:
    image: bitnami/kafka:4.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=2451c12e-a37d-4349-b744-a1047b01cbd3
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: unless-stopped
    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  clickhouse_data:
  kafka_data: