services:
  clickhouse:
    image: "clickhouse/clickhouse-server"
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: testanalytics-user
      CLICKHOUSE_PASSWORD: 123123