version: '3'

tasks:
  db:
    run: once
    cmds:
      - docker compose up -d
    silent: false

  actualize-db:
    run: once
    cmds:
      - dotnet run --project ActualizeDb.Cli/ActualizeDb.Cli.csproj
    silent: false

  api:
    deps: [actualize-db]
    cmds:
      - dotnet watch run --project TestCity.Api/TestCity.Api.csproj
    silent: false

  crawler:
    deps: [actualize-db]
    cmds:
      - dotnet watch run --project TestCity.GitLabJobsCrawler/TestCity.GitLabJobsCrawler.csproj
    silent: false

  front:
    dir: Front
    cmds:
      - npm install
      - npm start
    silent: false

  dev:
    deps: [db, api, crawler, front]
    silent: false

