version: '3'

tasks:
  db:
    cmds:
      - docker compose up
    silent: false

  clean-db:
    desc: Удалить все данные ClickHouse и Kafka (volume)
    cmds:
      - docker compose down -v
    silent: false

  actualize-db:
    run: once
    cmds:
      - dotnet run --project ActualizeDb.Cli/ActualizeDb.Cli.csproj --add-predefined-projects
    silent: false

  api:
    cmds:
      - dotnet watch run --project TestCity.Api/TestCity.Api.csproj
    silent: false

  worker:
    cmds:
      - dotnet watch run --project TestCity.Worker/TestCity.Worker.csproj
    silent: false

  crawler:
    cmds:
      - dotnet watch run --project TestCity.GitLabJobsCrawler/TestCity.GitLabJobsCrawler.csproj
    silent: false

  front:
    dir: Front
    cmds:
      - npm install
      - npm start
    silent: false

  # Задачи для dev окружения с зависимостью от actualize-db
  dev-api:
    deps: [actualize-db]
    cmds:
      - task: api
    silent: false

  dev-worker:
    deps: [actualize-db]
    cmds:
      - task: worker
    silent: false

  dev-crawler:
    deps: [actualize-db]
    cmds:
      - task: crawler
    silent: false

  dev:
    deps: [db, dev-api, dev-worker, dev-crawler, front]
    silent: false

