apiVersion: v1
kind: Service
metadata:
  name: test-city-front-service
  labels:
    app: {{ .Values.front.name }}
    {{- include "testcity.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.front.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.front.service.port }}
      targetPort: {{ .Values.front.service.targetPort }}
  type: {{ .Values.front.service.type }}
