name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        run: |
          VERSION=$(grep 'version:' ./charts/testcity/Chart.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Build and push TestCity.GitLabJobsCrawler
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.TestCity.GitLabJobsCrawler
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            tihonove/testcity-crawler:${{ env.VERSION }}
          cache-from: type=registry,ref=tihonove/testcity-crawler:${{ env.VERSION }}
          cache-to: type=inline
      
      - name: Build and push TestCity.Api
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.TestCity.Api
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            tihonove/testcity-api:${{ env.VERSION }}
          cache-from: type=registry,ref=tihonove/testcity-api:${{ env.VERSION }}
          cache-to: type=inline
      
      - name: Build and push Front
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.Front
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            tihonove/testcity-front:${{ env.VERSION }}
          cache-from: type=registry,ref=tihonove/testcity-front:${{ env.VERSION }}
          cache-to: type=inline
      
      - name: Build and push Worker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.Worker
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            tihonove/testcity-worker:${{ env.VERSION }}
          cache-from: type=registry,ref=tihonove/testcity-worker:${{ env.VERSION }}
          cache-to: type=inline

  publish-helm-chart:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name != 'pull_request'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.17.0'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Login to Docker Hub via helm
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          helm registry login registry-1.docker.io -u "$DOCKERHUB_USERNAME" --password-stdin <<<"$DOCKERHUB_TOKEN"
          
      - name: Package Helm chart
        run: |
          helm package ./charts/testcity
          
      - name: Push Helm chart to Docker Hub
        run: |
          helm push testcity-*.tgz oci://registry-1.docker.io/tihonove
